import { BoardKeyData, BoardKeySet } from "../board-layout";

export const KeyData = {
    esc: new BoardKeyData('esc', 'Escape'),
    f1: new BoardKeyData('f1', 'F1'),
    f2: new BoardKeyData('f2', 'F2'),
    f3: new BoardKeyData('f3', 'F3'),
    f4: new BoardKeyData('f4', 'F4'),
    f5: new BoardKeyData('f5', 'F5'),
    f6: new BoardKeyData('f6', 'F6'),
    f7: new BoardKeyData('f7', 'F7'),
    f8: new BoardKeyData('f8', 'F8'),
    f9: new BoardKeyData('f9', 'F9'),
    f10: new BoardKeyData('f10', 'F10'),
    f11: new BoardKeyData('f11', 'F11'),
    f12: new BoardKeyData('f12', 'F12'),
    prt: new BoardKeyData('prt', 'PrintScreen'),
    scr: new BoardKeyData('scr', 'ScrollLock'),
    pse: new BoardKeyData('pse', 'Pause'),

    backtick: new BoardKeyData('`', 'Backquote'),
    dig1: new BoardKeyData('1', 'Digit1'),
    dig2: new BoardKeyData('2', 'Digit2'),
    dig3: new BoardKeyData('3', 'Digit3'),
    dig4: new BoardKeyData('4', 'Digit4'),
    dig5: new BoardKeyData('5', 'Digit5'),
    dig6: new BoardKeyData('6', 'Digit6'),
    dig7: new BoardKeyData('7', 'Digit7'),
    dig8: new BoardKeyData('8', 'Digit8'),
    dig9: new BoardKeyData('9', 'Digit9'),
    dig0: new BoardKeyData('0', 'Digit0'),
    minus: new BoardKeyData('-', 'Minus'),
    equal: new BoardKeyData('=', 'Equal'),

    bksp: new BoardKeyData('bksp', 'Backspace'),
    ins: new BoardKeyData('ins', 'Insert'),
    hom: new BoardKeyData('hom', 'Home'),
    pgup: new BoardKeyData('pup', 'PageUp'),
    pgdn: new BoardKeyData('pdn', 'PageDown'),
    tab: new BoardKeyData('tab', 'Tab'),
    a: new BoardKeyData('a', 'KeyA'),
    b: new BoardKeyData('b', 'KeyB'),
    c: new BoardKeyData('c', 'KeyC'),
    d: new BoardKeyData('d', 'KeyD'),
    e: new BoardKeyData('e', 'KeyE'),
    f: new BoardKeyData('f', 'KeyF'),
    g: new BoardKeyData('g', 'KeyG'),
    h: new BoardKeyData('h', 'KeyH'),
    i: new BoardKeyData('i', 'KeyI'),
    j: new BoardKeyData('j', 'KeyJ'),
    k: new BoardKeyData('k', 'KeyK'),
    l: new BoardKeyData('l', 'KeyL'),
    m: new BoardKeyData('m', 'KeyM'),
    n: new BoardKeyData('n', 'KeyN'),
    o: new BoardKeyData('o', 'KeyO'),
    p: new BoardKeyData('p', 'KeyP'),
    q: new BoardKeyData('q', 'KeyQ'),
    r: new BoardKeyData('r', 'KeyR'),
    s: new BoardKeyData('s', 'KeyS'),
    t: new BoardKeyData('t', 'KeyT'),
    u: new BoardKeyData('u', 'KeyU'),
    v: new BoardKeyData('v', 'KeyV'),
    w: new BoardKeyData('w', 'KeyW'),
    x: new BoardKeyData('x', 'KeyX'),
    y: new BoardKeyData('y', 'KeyY'),
    z: new BoardKeyData('z', 'KeyZ'),

    bracketLeft: new BoardKeyData('[', 'BracketLeft'),
    bracketRight: new BoardKeyData(']', 'BracketRight'),
    del: new BoardKeyData('del', 'Delete'),
    end: new BoardKeyData('end', 'End'),
    backslash: new BoardKeyData('\\', 'Backslash'),

    caps: new BoardKeyData('caps', 'CapsLock'),
    enter: new BoardKeyData('enter', 'Enter'),
    semicolon: new BoardKeyData(';', 'Semicolon'),
    quote: new BoardKeyData('\'', 'Quote'),
    shiftLeft: new BoardKeyData("shift", "ShiftLeft"),
    shiftRight: new BoardKeyData("shift", "ShiftRight"),

    comma: new BoardKeyData(',', 'Comma'),
    period: new BoardKeyData('.', 'Period'),
    fwdslash: new BoardKeyData('/', 'Slash'),

    up: new BoardKeyData('up', 'ArrowUp'),
    down: new BoardKeyData('down', 'ArrowDown'),
    right: new BoardKeyData('right', 'ArrowRight'),
    left: new BoardKeyData('left', 'ArrowLeft'),

    ctrlLeft: new BoardKeyData('ctrl', 'ControlLeft'),
    ctrlRight: new BoardKeyData('ctrl', 'ControlRight'),
    winkey: new BoardKeyData('win', 'MetaLeft'),
    altLeft: new BoardKeyData('alt', 'AltLeft'),
    altRight: new BoardKeyData('alt', 'AltRight'),
    menu: new BoardKeyData('menu', 'MetaRight'),
    fn: new BoardKeyData('fn', ''),
    space: new BoardKeyData('', 'Space'),
}
